Repository seekinternational/seek-asia-style-guide, pull requests merged in 2019-05, with the labels that each got.

#393 fix(JobCard): Update UI
  react/JobCard/JobCard.less
Labels: not ready for review

#378 fix(SlideToggle): Refactor component
  react/SlideToggle/SlideToggle.demo.js
  react/SlideToggle/SlideToggle.js
  react/SlideToggle/SlideToggle.less
  react/SlideToggle/SlideToggle.sketch.js
  react/SlideToggle/SlideToggle.test.js
  react/SlideToggle/__snapshots__/SlideToggle.test.js.snap
Labels: accessibility, css, enhancement

#395 fix(button): Style hygiene
  react/Button/Button.demo.js
  react/Button/Button.less
Labels: css

#398 Feature/additional show more props
  react/ShowMore/ShowMore.demo.js
  react/ShowMore/ShowMore.js
  react/ShowMore/ShowMore.less
  react/ShowMore/ShowMore.sketch.js
  react/ShowMore/ShowMore.test.js
  react/ShowMore/__snapshots__/ShowMore.test.js.snap
Labels: enhancement

#406 Update menu item style
  docs/src/components/App/Header/Header.js
  docs/src/components/App/Header/Header.less
Labels: accessibility, css, enhancement
