Repository seekinternational/seek-asia-style-guide, pull requests merged in 2019-09, with the labels that each got.

#447 fix(Icon): Dynamic type in prop types to prevent missing types
  react/Icon/Icon.js
Labels: bug

#450 fix(Checkbox): Style clean up
  react/Checkbox/Checkbox.js
  react/Checkbox/Checkbox.less
  react/Checkbox/Checkbox.sketch.js
  react/Checkbox/__snapshots__/Checkbox.test.js.snap
Labels: Clean up, browser bug, css

#448 fix(listItem): Style clean up
  react/ListItem/ListItem.less
Labels: Clean up, browser bug, css

#451 fix(Checkbox): Fix onChange issue
  react/Checkbox/Checkbox.demo.js
  react/Checkbox/Checkbox.js
  react/Checkbox/__snapshots__/Checkbox.test.js.snap
Labels: bug

#453 fix(Checkbox): Fix box not clickable issue
  react/Checkbox/Checkbox.js
  react/Checkbox/Checkbox.sketch.js
  react/Checkbox/__snapshots__/Checkbox.test.js.snap
Labels: bug

#459 fix(Footer): Fix flexbox item placement beyond mobile breakpoints
  react/private/GlobalFooter/components/FooterLinks/FooterLinks.less
  react/private/GlobalFooter/components/UpperFooter/UpperFooter.less
Labels: browser bug, css
